### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems' from local DRF with swagger docs

### ISSUE THREAD

**Issue by RadoRado** [core-api/coredocs#8]
I decided to test the following scenario with `coredocs`:

1. There's a DRF (latest version)
2. Added DRF Rest Swagger (latest version)
3. `$ coredocs build "http://localhost:8000/docs?format=openapi" --format openapi` results in the following exception:

```
Fetching schema file from 'http://localhost:8000/docs?format=openapi'.
Traceback (most recent call last):
  File "/home/radorado/code/python-envs/drfjwt/bin/coredocs", line 11, in <module>
    sys.exit(client())
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/coredocs/main.py", line 136, in build
    output_text = render(document, highlight, languages, theme=theme)
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/coredocs/main.py", line 54, in render
    schema_format=schema_format
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/coredocs/themes/slate/templates/index.html", line 44, in top-level template code
    {% include "document.html" %}
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/coredocs/themes/base/templates/document.html", line 5, in top-level template code
    {% for section_key, section in get_sections(document) %}
  File "/home/radorado/code/python-envs/drfjwt/lib/python3.5/site-packages/coredocs/utils.py", line 14, in get_sections
    return sorted(node.data.iteritems(), key=lambda item: item[0])
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'

```

Am I doing something wrong? :panda_face:

**Comment by RadoRado** [comment]
The JSON:

```
{
    "swagger":"2.0",
    "info":{
        "title":"Swagger API View",
        "version":""
    },
    "paths":{
        "/stuff/panda/list/":{
            "get":{
                "parameters":[
                    {
                        "name":"page",
                        "description":"",
                        "type":"string",
                        "required":false,
                        "in":"query"
                    }
                ],
                "operationId":"list",
                "tags":[
                    "list"
                ],
                "responses":{
                    "200":{
                        "description":""
                    }
                }
            }
        }
    },
    "securityDefinitions":{
        "basic":{
            "type":"basic"
        }
    }
}
```

**Comment by francescarpi** [comment]
I have same issue.

Python 3.5.2
coredocs 0.0.6

**Comment by francescarpi** [comment]
Works fine with Python2.7. I think that isn't compatible with Python3.

**Comment by carltongibson** [comment]
This was already changed in https://github.com/core-api/coredocs/commit/6c833c549deb9fde37a82957c9889fecf5a1f546#diff-8f109129a8007856c028c2dc21457a3c

But it's not in the latest release https://github.com/core-api/coredocs/compare/0.0.6...master

So, for now, you'll need to work off of `master`

**Comment by ferndot** [comment]
It would be very helpful if this fix could be uploaded to PYPI. What do you think?
